services:
  postgres:
    image: postgres:16-alpine
    container_name: flashme-db
    environment:
      POSTGRES_USER: flashme
      POSTGRES_PASSWORD: flashme
      POSTGRES_DB: flashme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
